#
# OrangeFox settings
OF_HIDE_NOTCH := 1
OF_USE_GREEN_LED := 0
OF_FLASHLIGHT_ENABLE := 1
OF_ALLOW_DISABLE_NAVBAR := 0
OF_AB_DEVICE_WITH_RECOVERY_PARTITION := 1
OF_RECOVERY_AB_FULL_REFLASH_RAMDISK := 1
OF_USE_MAGISKBOOT := 1
OF_SKIP_FBE_DECRYPTION_SDKVERSION := 1
OF_BIND_MOUNT_SDCARD_ON_FORMAT := 1


# Maximum permissible splash image size (in kilobytes); do *NOT* increase
OF_SPLASH_MAX_SIZ
# Custom pic for maintainers about section info
OF_MAINTAINER := 404xG31

# OrangeFox GUI settings
OF_SCREEN_H := 2280
OF_STATUS_H := 100
OF_STATUS_INDENT_LEFT := 48
OF_STATUS_INDENT_RIGHT := 48
OF_HIDE_NOTCH := 1
OF_CLOCK_POS := 1
OF_OPTIONS_LIST_NUM := 6
